In [1]:
import os
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Numpy Basics

In [2]:
lis = [0,1,2,3,4]
type(lis)

list

In [3]:
array = np.array(lis)
array

array([0, 1, 2, 3, 4])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 1D array containing 5 zeros 

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# 2D array containing 5*7 zeroes
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.ones((5,7))*10

array([[10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.]])

In [10]:
# To generate random integers, start range, end range, number of random numbers
np.random.randint(0,100,10)

array([59, 30, 94, 94,  2, 79, 82, 13, 16, 63])

In [11]:
# can change the shape of above array using .reshape
np.random.randint(0,100,10).reshape(2,5)

# Everytime we run this, we will get a different output

array([[37, 21, 94, 35, 80],
       [99, 56, 68, 70, 84]])

In [12]:
#Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(25)

array([-1.96092899, -0.83684318,  0.32535963,  0.18958159,  0.38400012,
        1.07575216, -0.14789393, -0.23139763, -1.29008128,  1.25944388,
        0.49631607, -0.16174851,  1.84567965,  0.65525094, -1.56839029,
       -1.56841164,  1.2627148 ,  0.40689125,  1.06168863,  0.69503473,
       -1.20469732,  1.13374653,  0.4556833 , -0.25004352,  0.76120371])

In [13]:
#Return random floats in the half-open interval [0.0, 1.0]
np.random.random(25)

array([0.39528742, 0.35383921, 0.89122563, 0.77080858, 0.12854594,
       0.52268151, 0.13894669, 0.55491969, 0.82257161, 0.19176537,
       0.27098378, 0.45266681, 0.68595107, 0.1135046 , 0.72798028,
       0.86449709, 0.9432569 , 0.60379355, 0.4940919 , 0.41911029,
       0.86857833, 0.05155039, 0.08603306, 0.58367566, 0.87824688])

In [14]:
np.random.random(25).reshape(5,5)

array([[0.71727026, 0.12124956, 0.52414997, 0.29954166, 0.1867288 ],
       [0.14298927, 0.72514495, 0.69058826, 0.51824333, 0.16898631],
       [0.6666055 , 0.13889658, 0.7741022 , 0.79528783, 0.43382512],
       [0.27629154, 0.51939227, 0.31961299, 0.9287645 , 0.31632205],
       [0.73218687, 0.59000588, 0.78623169, 0.72532031, 0.28298208]])

In [15]:
# To get the same value or to fix the randomness, we use seed function
# in the same cell as np.random
np.random.seed(101)  # we can use any number inside seed. each number has fixed assigned randomness
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [16]:
arr.max()

95

In [17]:
arr.min()

9

In [18]:
# To get the index of the max and min elements, we use
print(arr.argmax())
print(arr.argmin())

0
7


In [19]:
matrix = np.arange(0,100).reshape(10,10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
# to get a subarray
matrix[7:9,3:4]

array([[73],
       [83]])

In [21]:
# to get an element
matrix[2,8]

28

### Drawing images and shapes using openCV
- drawing a black image
- drawing a black and white image

In [22]:
image = np.ones((512,512,3),np.uint8)*255 # 3 channel
image_bw = np.zeros((512,512),np.uint8)
# uint = datatype (unsigned integer 0-255)

In [23]:
cv2.imshow("White_image",image) # white image because it is np.ones
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
cv2.imshow("black and white",image_bw)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 1. Drawing a line over the black image

    cv2.line(image,starting coord, ending coord, color, thickness)

- uint data type: contains all whole numbers from 0 to 255. As with all unsigned numbers value must be non-negative. Mostly used in graphics(clors are always non-negative)

In [25]:
image = np.ones((512,512,3),np.uint8)*0
cv2.line(image,(5,7),(233,233),(255,0,0),5)
cv2.imshow("line",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 2. Drawing a rectangle over the previous image

    cv2.rectangle(image,starting vertex, opposite vertex, color, thickness)

In [26]:
# image = np.ones((512,512,3),np.uint8)*0
cv2.rectangle(image,(5,7),(233,233),(0,0,255),10)
cv2.imshow("Rectangle",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 3. Drawing a circle

    cv2.circle(image,center,radius,color,fill)

In [27]:
image = np.ones((512,512,3),np.uint8)*0
cv2.circle(image,(300,300),50,(0,255,255),-1) # -1 is for filled circle
cv2.imshow("circle",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 4. Drawing a polygons

In [29]:
image = np.ones((512,512,3),np.uint8)*0
pts = np.array([[10,50],[400,50],[90,200],[80,75]],np.int32)
pts = pts.reshape((-1,1,2))
cv2.polylines(image,[pts],True,(0,0,255),3) # True = to join 1st and last coordinates
cv2.imshow("polygon",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 5. Putting text inside the image

    cv2.putText(image,"text to display",bottom left start point,font,fontsize,color,thickness)

In [30]:
image = np.ones((512,512,3),np.uint8)*0
cv2.putText(image,"Helloooo",(100,200),cv2.FONT_HERSHEY_DUPLEX,2,(213,244,0),3)
cv2.imshow("text",image)
cv2.waitKey(0)
cv2.destroyAllWindows()